"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
from . import channel_pb2
from . import config_pb2
from . import localonly_pb2
from . import mesh_pb2
from . import telemetry_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class PositionLite(google.protobuf.message.Message):
    """
    Position with static location information only for NodeDBLite
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LATITUDE_I_FIELD_NUMBER: builtins.int
    LONGITUDE_I_FIELD_NUMBER: builtins.int
    ALTITUDE_FIELD_NUMBER: builtins.int
    TIME_FIELD_NUMBER: builtins.int
    LOCATION_SOURCE_FIELD_NUMBER: builtins.int
    PRECISION_BITS_FIELD_NUMBER: builtins.int
    latitude_i: builtins.int
    """
    The new preferred location encoding, multiply by 1e-7 to get degrees
    in floating point
    """
    longitude_i: builtins.int
    """
    TODO: REPLACE
    """
    altitude: builtins.int
    """
    In meters above MSL (but see issue #359)
    """
    time: builtins.int
    """
    This is usually not sent over the mesh (to save space), but it is sent
    from the phone so that the local device can set its RTC If it is sent over
    the mesh (because there are devices on the mesh without GPS), it will only
    be sent by devices which has a hardware GPS clock.
    seconds since 1970
    """
    location_source: mesh_pb2.Position.LocSource.ValueType
    """
    TODO: REPLACE
    """
    precision_bits: builtins.int
    """
    Indicates the bits of precision set by the sending node
    """
    def __init__(
        self,
        *,
        latitude_i: builtins.int = ...,
        longitude_i: builtins.int = ...,
        altitude: builtins.int = ...,
        time: builtins.int = ...,
        location_source: mesh_pb2.Position.LocSource.ValueType = ...,
        precision_bits: builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["altitude", b"altitude", "latitude_i", b"latitude_i", "location_source", b"location_source", "longitude_i", b"longitude_i", "precision_bits", b"precision_bits", "time", b"time"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PositionLite: typing_extensions.TypeAlias = PositionLite

@typing.final
class UserLite(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MACADDR_FIELD_NUMBER: builtins.int
    LONG_NAME_FIELD_NUMBER: builtins.int
    SHORT_NAME_FIELD_NUMBER: builtins.int
    HW_MODEL_FIELD_NUMBER: builtins.int
    IS_LICENSED_FIELD_NUMBER: builtins.int
    ROLE_FIELD_NUMBER: builtins.int
    PUBLIC_KEY_FIELD_NUMBER: builtins.int
    IS_UNMESSAGABLE_FIELD_NUMBER: builtins.int
    macaddr: builtins.bytes
    """
    This is the addr of the radio.
    """
    long_name: builtins.str
    """
    A full name for this user, i.e. "Kevin Hester"
    """
    short_name: builtins.str
    """
    A VERY short name, ideally two characters.
    Suitable for a tiny OLED screen
    """
    hw_model: mesh_pb2.HardwareModel.ValueType
    """
    TBEAM, HELTEC, etc...
    Starting in 1.2.11 moved to hw_model enum in the NodeInfo object.
    Apps will still need the string here for older builds
    (so OTA update can find the right image), but if the enum is available it will be used instead.
    """
    is_licensed: builtins.bool
    """
    In some regions Ham radio operators have different bandwidth limitations than others.
    If this user is a licensed operator, set this flag.
    Also, "long_name" should be their licence number.
    """
    role: config_pb2.Config.DeviceConfig.Role.ValueType
    """
    Indicates that the user's role in the mesh
    """
    public_key: builtins.bytes
    """
    The public key of the user's device.
    This is sent out to other nodes on the mesh to allow them to compute a shared secret key.
    """
    is_unmessagable: builtins.bool
    """
    Whether or not the node can be messaged
    """
    def __init__(
        self,
        *,
        macaddr: builtins.bytes = ...,
        long_name: builtins.str = ...,
        short_name: builtins.str = ...,
        hw_model: mesh_pb2.HardwareModel.ValueType = ...,
        is_licensed: builtins.bool = ...,
        role: config_pb2.Config.DeviceConfig.Role.ValueType = ...,
        public_key: builtins.bytes = ...,
        is_unmessagable: builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["_is_unmessagable", b"_is_unmessagable", "is_unmessagable", b"is_unmessagable"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["_is_unmessagable", b"_is_unmessagable", "hw_model", b"hw_model", "is_licensed", b"is_licensed", "is_unmessagable", b"is_unmessagable", "long_name", b"long_name", "macaddr", b"macaddr", "public_key", b"public_key", "role", b"role", "short_name", b"short_name"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__is_unmessagable: typing_extensions.TypeAlias = typing.Literal["is_unmessagable"]
    _WhichOneofArgType__is_unmessagable: typing_extensions.TypeAlias = typing.Literal["_is_unmessagable", b"_is_unmessagable"]
    def WhichOneof(self, oneof_group: _WhichOneofArgType__is_unmessagable) -> _WhichOneofReturnType__is_unmessagable | None: ...

Global___UserLite: typing_extensions.TypeAlias = UserLite

@typing.final
class NodeInfoLite(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NUM_FIELD_NUMBER: builtins.int
    SNR_FIELD_NUMBER: builtins.int
    LAST_HEARD_FIELD_NUMBER: builtins.int
    CHANNEL_FIELD_NUMBER: builtins.int
    HOPS_AWAY_FIELD_NUMBER: builtins.int
    NEXT_HOP_FIELD_NUMBER: builtins.int
    BITFIELD_FIELD_NUMBER: builtins.int
    LONG_NAME_FIELD_NUMBER: builtins.int
    SHORT_NAME_FIELD_NUMBER: builtins.int
    HW_MODEL_FIELD_NUMBER: builtins.int
    ROLE_FIELD_NUMBER: builtins.int
    PUBLIC_KEY_FIELD_NUMBER: builtins.int
    SNR_Q4_FIELD_NUMBER: builtins.int
    num: builtins.int
    """
    The node number
    """
    snr: builtins.float
    """
    In-memory SNR of the last received message in dB. Not serialised directly:
    always zeroed before encode; persisted as snr_q4 = 19 below.
    """
    last_heard: builtins.int
    """
    Set to indicate the last time we received a packet from this node
    """
    channel: builtins.int
    """
    local channel index we heard that node on. Only populated if its not the default channel.
    """
    hops_away: builtins.int
    """
    Number of hops away from us this node is (0 if direct neighbor)
    """
    next_hop: builtins.int
    """
    Last byte of the node number of the node that should be used as the next hop to reach this node.
    """
    bitfield: builtins.int
    """
    Bitfield for storing booleans. See NODEINFO_BITFIELD_* in src/mesh/NodeDB.h.
    """
    long_name: builtins.str
    """Flattened user fields (formerly UserLite). macaddr dropped (deprecated 1.2.11).


    A full name for this user, i.e. "Kevin Hester".
    """
    short_name: builtins.str
    """
    A VERY short name, ideally two characters or an emoji.
    Suitable for a tiny OLED screen.
    """
    hw_model: mesh_pb2.HardwareModel.ValueType
    """
    Hardware model the user's device is running.
    """
    role: config_pb2.Config.DeviceConfig.Role.ValueType
    """
    The user's role in the mesh.
    """
    public_key: builtins.bytes
    """
    The public key of the user's device, for PKI-based encrypted DMs.
    """
    snr_q4: builtins.int
    """
    Q4-encoded SNR: dB × 4, sint32 zigzag. Matches RouteDiscovery convention.
    Encode: snr_q4 = (int32_t)lroundf(snr * 4.0f). Decode: snr = snr_q4 / 4.0f.
    float snr is always zeroed on disk; this field carries all persisted SNR.
    A stored 0 does not by itself mean "unknown" here - see NODEINFO_BITFIELD_HAS_SNR in
    src/mesh/NodeDB.h for the presence bit that disambiguates a genuine 0 dB reading from
    "never measured".
    """
    def __init__(
        self,
        *,
        num: builtins.int = ...,
        snr: builtins.float = ...,
        last_heard: builtins.int = ...,
        channel: builtins.int = ...,
        hops_away: builtins.int | None = ...,
        next_hop: builtins.int = ...,
        bitfield: builtins.int = ...,
        long_name: builtins.str = ...,
        short_name: builtins.str = ...,
        hw_model: mesh_pb2.HardwareModel.ValueType = ...,
        role: config_pb2.Config.DeviceConfig.Role.ValueType = ...,
        public_key: builtins.bytes = ...,
        snr_q4: builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["_hops_away", b"_hops_away", "hops_away", b"hops_away"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["_hops_away", b"_hops_away", "bitfield", b"bitfield", "channel", b"channel", "hops_away", b"hops_away", "hw_model", b"hw_model", "last_heard", b"last_heard", "long_name", b"long_name", "next_hop", b"next_hop", "num", b"num", "public_key", b"public_key", "role", b"role", "short_name", b"short_name", "snr", b"snr", "snr_q4", b"snr_q4"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__hops_away: typing_extensions.TypeAlias = typing.Literal["hops_away"]
    _WhichOneofArgType__hops_away: typing_extensions.TypeAlias = typing.Literal["_hops_away", b"_hops_away"]
    def WhichOneof(self, oneof_group: _WhichOneofArgType__hops_away) -> _WhichOneofReturnType__hops_away | None: ...

Global___NodeInfoLite: typing_extensions.TypeAlias = NodeInfoLite

@typing.final
class DeviceState(google.protobuf.message.Message):
    """
    This message is never sent over the wire, but it is used for serializing DB
    state to flash in the device code
    FIXME, since we write this each time we enter deep sleep (and have infinite
    flash) it would be better to use some sort of append only data structure for
    the receive queue and use the preferences store for the other stuff
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MY_NODE_FIELD_NUMBER: builtins.int
    OWNER_FIELD_NUMBER: builtins.int
    RECEIVE_QUEUE_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    RX_TEXT_MESSAGE_FIELD_NUMBER: builtins.int
    NO_SAVE_FIELD_NUMBER: builtins.int
    DID_GPS_RESET_FIELD_NUMBER: builtins.int
    RX_WAYPOINT_FIELD_NUMBER: builtins.int
    NODE_REMOTE_HARDWARE_PINS_FIELD_NUMBER: builtins.int
    version: builtins.int
    """
    A version integer used to invalidate old save files when we make
    incompatible changes This integer is set at build time and is private to
    NodeDB.cpp in the device code.
    """
    no_save: builtins.bool
    """
    Used only during development.
    Indicates developer is testing and changes should never be saved to flash.
    Deprecated in 2.3.1
    """
    did_gps_reset: builtins.bool
    """
    Previously used to manage GPS factory resets.
    Deprecated in 2.5.23
    """
    @property
    def my_node(self) -> mesh_pb2.MyNodeInfo:
        """
        Read only settings/info about this node
        """

    @property
    def owner(self) -> mesh_pb2.User:
        """
        My owner info
        """

    @property
    def receive_queue(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[mesh_pb2.MeshPacket]:
        """
        Received packets saved for delivery to the phone
        """

    @property
    def rx_text_message(self) -> mesh_pb2.MeshPacket:
        """
        We keep the last received text message (only) stored in the device flash,
        so we can show it on the screen.
        Might be null
        """

    @property
    def rx_waypoint(self) -> mesh_pb2.MeshPacket:
        """
        We keep the last received waypoint stored in the device flash,
        so we can show it on the screen.
        Might be null
        """

    @property
    def node_remote_hardware_pins(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[mesh_pb2.NodeRemoteHardwarePin]:
        """
        The mesh's nodes with their available gpio pins for RemoteHardware module
        """

    def __init__(
        self,
        *,
        my_node: mesh_pb2.MyNodeInfo | None = ...,
        owner: mesh_pb2.User | None = ...,
        receive_queue: collections.abc.Iterable[mesh_pb2.MeshPacket] | None = ...,
        version: builtins.int = ...,
        rx_text_message: mesh_pb2.MeshPacket | None = ...,
        no_save: builtins.bool = ...,
        did_gps_reset: builtins.bool = ...,
        rx_waypoint: mesh_pb2.MeshPacket | None = ...,
        node_remote_hardware_pins: collections.abc.Iterable[mesh_pb2.NodeRemoteHardwarePin] | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["my_node", b"my_node", "owner", b"owner", "rx_text_message", b"rx_text_message", "rx_waypoint", b"rx_waypoint"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["did_gps_reset", b"did_gps_reset", "my_node", b"my_node", "no_save", b"no_save", "node_remote_hardware_pins", b"node_remote_hardware_pins", "owner", b"owner", "receive_queue", b"receive_queue", "rx_text_message", b"rx_text_message", "rx_waypoint", b"rx_waypoint", "version", b"version"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeviceState: typing_extensions.TypeAlias = DeviceState

@typing.final
class NodePositionEntry(google.protobuf.message.Message):
    """Satellite per-node entries; stored alongside the slim NodeInfoLite so nodes
    that never report don't pay the embedded cost.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NUM_FIELD_NUMBER: builtins.int
    POSITION_FIELD_NUMBER: builtins.int
    num: builtins.int
    @property
    def position(self) -> Global___PositionLite: ...
    def __init__(
        self,
        *,
        num: builtins.int = ...,
        position: Global___PositionLite | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["position", b"position"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["num", b"num", "position", b"position"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___NodePositionEntry: typing_extensions.TypeAlias = NodePositionEntry

@typing.final
class NodeTelemetryEntry(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NUM_FIELD_NUMBER: builtins.int
    DEVICE_METRICS_FIELD_NUMBER: builtins.int
    num: builtins.int
    @property
    def device_metrics(self) -> telemetry_pb2.DeviceMetrics: ...
    def __init__(
        self,
        *,
        num: builtins.int = ...,
        device_metrics: telemetry_pb2.DeviceMetrics | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["device_metrics", b"device_metrics"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["device_metrics", b"device_metrics", "num", b"num"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___NodeTelemetryEntry: typing_extensions.TypeAlias = NodeTelemetryEntry

@typing.final
class NodeEnvironmentEntry(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NUM_FIELD_NUMBER: builtins.int
    ENVIRONMENT_METRICS_FIELD_NUMBER: builtins.int
    num: builtins.int
    @property
    def environment_metrics(self) -> telemetry_pb2.EnvironmentMetrics: ...
    def __init__(
        self,
        *,
        num: builtins.int = ...,
        environment_metrics: telemetry_pb2.EnvironmentMetrics | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["environment_metrics", b"environment_metrics"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["environment_metrics", b"environment_metrics", "num", b"num"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___NodeEnvironmentEntry: typing_extensions.TypeAlias = NodeEnvironmentEntry

@typing.final
class NodeStatusEntry(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NUM_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    num: builtins.int
    @property
    def status(self) -> mesh_pb2.StatusMessage: ...
    def __init__(
        self,
        *,
        num: builtins.int = ...,
        status: mesh_pb2.StatusMessage | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["status", b"status"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["num", b"num", "status", b"status"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___NodeStatusEntry: typing_extensions.TypeAlias = NodeStatusEntry

@typing.final
class NodeDatabase(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VERSION_FIELD_NUMBER: builtins.int
    NODES_FIELD_NUMBER: builtins.int
    POSITIONS_FIELD_NUMBER: builtins.int
    TELEMETRY_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    ENVIRONMENT_FIELD_NUMBER: builtins.int
    version: builtins.int
    """
    A version integer used to invalidate old save files when we make
    incompatible changes This integer is set at build time and is private to
    NodeDB.cpp in the device code.
    """
    @property
    def nodes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___NodeInfoLite]:
        """
        New lite version of NodeDB to decrease memory footprint
        """

    @property
    def positions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___NodePositionEntry]:
        """Per-NodeNum satellite arrays. Constrained platforms (e.g. STM32WL) omit
        these via MESHTASTIC_EXCLUDE_*DB build flags.
        """

    @property
    def telemetry(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___NodeTelemetryEntry]: ...
    @property
    def status(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___NodeStatusEntry]: ...
    @property
    def environment(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___NodeEnvironmentEntry]: ...
    def __init__(
        self,
        *,
        version: builtins.int = ...,
        nodes: collections.abc.Iterable[Global___NodeInfoLite] | None = ...,
        positions: collections.abc.Iterable[Global___NodePositionEntry] | None = ...,
        telemetry: collections.abc.Iterable[Global___NodeTelemetryEntry] | None = ...,
        status: collections.abc.Iterable[Global___NodeStatusEntry] | None = ...,
        environment: collections.abc.Iterable[Global___NodeEnvironmentEntry] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["environment", b"environment", "nodes", b"nodes", "positions", b"positions", "status", b"status", "telemetry", b"telemetry", "version", b"version"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___NodeDatabase: typing_extensions.TypeAlias = NodeDatabase

@typing.final
class ChannelFile(google.protobuf.message.Message):
    """
    The on-disk saved channels
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHANNELS_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    version: builtins.int
    """
    A version integer used to invalidate old save files when we make
    incompatible changes This integer is set at build time and is private to
    NodeDB.cpp in the device code.
    """
    @property
    def channels(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[channel_pb2.Channel]:
        """
        The channels our node knows about
        """

    def __init__(
        self,
        *,
        channels: collections.abc.Iterable[channel_pb2.Channel] | None = ...,
        version: builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["channels", b"channels", "version", b"version"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ChannelFile: typing_extensions.TypeAlias = ChannelFile

@typing.final
class BackupPreferences(google.protobuf.message.Message):
    """
    The on-disk backup of the node's preferences
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VERSION_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    CONFIG_FIELD_NUMBER: builtins.int
    MODULE_CONFIG_FIELD_NUMBER: builtins.int
    CHANNELS_FIELD_NUMBER: builtins.int
    OWNER_FIELD_NUMBER: builtins.int
    version: builtins.int
    """
    The version of the backup
    """
    timestamp: builtins.int
    """
    The timestamp of the backup (if node has time)
    """
    @property
    def config(self) -> localonly_pb2.LocalConfig:
        """
        The node's configuration
        """

    @property
    def module_config(self) -> localonly_pb2.LocalModuleConfig:
        """
        The node's module configuration
        """

    @property
    def channels(self) -> Global___ChannelFile:
        """
        The node's channels
        """

    @property
    def owner(self) -> mesh_pb2.User:
        """
        The node's user (owner) information
        """

    def __init__(
        self,
        *,
        version: builtins.int = ...,
        timestamp: builtins.int = ...,
        config: localonly_pb2.LocalConfig | None = ...,
        module_config: localonly_pb2.LocalModuleConfig | None = ...,
        channels: Global___ChannelFile | None = ...,
        owner: mesh_pb2.User | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["channels", b"channels", "config", b"config", "module_config", b"module_config", "owner", b"owner"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["channels", b"channels", "config", b"config", "module_config", b"module_config", "owner", b"owner", "timestamp", b"timestamp", "version", b"version"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BackupPreferences: typing_extensions.TypeAlias = BackupPreferences
